tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Distributed revision control system
brew "git"
# Improved top (interactive process viewer)
brew "htop"
# Remote terminal application
brew "mosh"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Platform built on V8 to build network applications
brew "node"
# Utility that provides fast incremental file transfer
brew "rsync"
# Terminal multiplexer
brew "tmux"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# UNIX shell (command interpreter)
brew "zsh"
cask "telegram"
